### PR TITLE
Update EasyNetQ and RabbitMQ.Client to latest versions.

### PR DESCRIPTION
**Pull request by slovely**
Hi,

This PR contains updated references to the `EasyNetQ` and `RabbitMQ.Client` packages.  v3.5 of `RabbitMQ.Client` had a breaking change which was fixed in v0.5 of `EasyNetQ`.  The only code change required was in `RabbitConnectionBase` - the event handler signatures were changed.

### CODE REVIEW

**Comment by mdevilliers** [comment]
Cool thanks.

I'll try and have a look at this tonight with my smoke tests.

**Comment by slovely** [comment]
Thanks Mark - please let me know if I can help further.

**Comment by mdevilliers** [comment]
Looks good to me.

Thanks for the PR - really appreciate it.

**Comment by slovely** [comment]
Thanks for looking at it so quickly.

Looks good to me.

Thanks for the PR - really appreciate it.

—
Reply to this email directly or view it on GitHub
<https://github.com/mdevilliers/SignalR.RabbitMq/pull/38#issuecomment-140507905>
.

**Pull request merged**
